import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// 메타데이터 설정
export const metadata: Metadata = {
  title: "Next Quiz App",
  description: "Generated by create next app",
};
// Readonly 읽기 전용 속성, children 타입 React.ReactNode
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className='bg-gray-50'>
        <div className='bg-slate-200 max-w-7xl mx-auto  shadow-xl  border-1 min-h-[52rem] border-gray-600'>
          <Header />
          {children}

        </div>
        <footer className={'max-w-7xl mx-auto bg-orange-500 p-10 text-center text-slate-200'}>
          <Link href="https://github.com/SIM-TOO">
            <p>@SIM-TOO</p>
          </Link>
        </footer>
      </body>
    </html>
  );
}
